// <auto-generated />
using DeteksiJalanRusak.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeteksiJalanRusak.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204034412_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Analisis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblAnalisis");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.FotoKerusakan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdaKertas")
                        .HasColumnType("boolean");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lebar")
                        .HasColumnType("double precision");

                    b.Property<double?>("LebarKertas")
                        .HasColumnType("double precision");

                    b.Property<double?>("LuasKertas")
                        .HasColumnType("double precision");

                    b.Property<double>("M2PerPiksel")
                        .HasColumnType("double precision");

                    b.Property<double>("MPerPiksel")
                        .HasColumnType("double precision");

                    b.Property<string>("Mask64Kertas")
                        .HasColumnType("text");

                    b.Property<double?>("PanjangKertas")
                        .HasColumnType("double precision");

                    b.Property<int>("SegmenId")
                        .HasColumnType("integer");

                    b.Property<double>("Tinggi")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SegmenId");

                    b.ToTable("TblFoto");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Kerusakan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FotoKerusakanId")
                        .HasColumnType("integer");

                    b.Property<int>("Label")
                        .HasColumnType("integer");

                    b.Property<double>("Lebar")
                        .HasColumnType("double precision");

                    b.Property<double>("Luas")
                        .HasColumnType("double precision");

                    b.Property<string>("MaskBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Panjang")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FotoKerusakanId");

                    b.ToTable("TblKerusakan");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Segmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalisisId")
                        .HasColumnType("integer");

                    b.Property<double>("LuasSampel")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnalisisId");

                    b.ToTable("TblSegmen");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.FotoKerusakan", b =>
                {
                    b.HasOne("DeteksiJalanRusak.Web.Entities.Segmen", "Segmen")
                        .WithMany("DaftarFoto")
                        .HasForeignKey("SegmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segmen");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Kerusakan", b =>
                {
                    b.HasOne("DeteksiJalanRusak.Web.Entities.FotoKerusakan", "FotoKerusakan")
                        .WithMany("DaftarKerusakan")
                        .HasForeignKey("FotoKerusakanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FotoKerusakan");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Segmen", b =>
                {
                    b.HasOne("DeteksiJalanRusak.Web.Entities.Analisis", "Analisis")
                        .WithMany("DaftarSegmen")
                        .HasForeignKey("AnalisisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Analisis", b =>
                {
                    b.Navigation("DaftarSegmen");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.FotoKerusakan", b =>
                {
                    b.Navigation("DaftarKerusakan");
                });

            modelBuilder.Entity("DeteksiJalanRusak.Web.Entities.Segmen", b =>
                {
                    b.Navigation("DaftarFoto");
                });
#pragma warning restore 612, 618
        }
    }
}
